### PR TITLE
Allow BASE to be set from environment

### PR DESCRIPTION
**Pull request by brewlius-cesar**
Needed for PR pyne/pyne#735

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @brewlius-cesar - can you also update the readme here to say that you can set BASE in the environment, please?

**Comment by scopatz** [comment]
This seems to work, otherwise! Thanks!

**Comment by brewlius-cesar** [comment]
No problem, readme.md is updated.  Once this is merged the changes should align with the changes made to .travis.yaml in pyne/pyne

P.S. Thanks for putting together such a great tool!

**Comment by scopatz** [comment]
> P.S. Thanks for putting together such a great tool!

Thanks to you for helping :)

**Pull request merged**
